#pragma once

const int FEATURE_TYPE_INDEX = 0;  
const int SPLIT_POINT_INDEX = FEATURE_TYPE_INDEX; 
const int FEATURE_SPECIFIC_PARAMS_START = FEATURE_TYPE_INDEX + 1;
const int LEFT_CHILD = 0;
const int RIGHT_CHILD = 1;