#include "MatrixBuffer.h"


#define DEFINE_SWIG_INTERFACE_FUNCTION_2D(TYPE_PREFIX, TYPE, TYPE_VAR) \
TYPE_PREFIX ## MatrixBuffer TYPE_PREFIX ## Matrix2(TYPE* TYPE_VAR ## 2d, int m, int n) \
{ \
    return TYPE_PREFIX ## MatrixBuffer(TYPE_VAR ## 2d, m, n); \
}

DEFINE_SWIG_INTERFACE_FUNCTION_2D(Float32, float, float)
DEFINE_SWIG_INTERFACE_FUNCTION_2D(Float64, double, double)
DEFINE_SWIG_INTERFACE_FUNCTION_2D(Int32, int, int)
DEFINE_SWIG_INTERFACE_FUNCTION_2D(Int64, long long, long)

#define DEFINE_SWIG_INTERFACE_FUNCTION_1D(TYPE_PREFIX, TYPE, TYPE_VAR) \
TYPE_PREFIX ## MatrixBuffer TYPE_PREFIX ## Matrix1(TYPE* TYPE_VAR ## 1d, int n) \
{ \
    return TYPE_PREFIX ## MatrixBuffer(TYPE_VAR ## 1d, n, 1); \
}

DEFINE_SWIG_INTERFACE_FUNCTION_1D(Float32, float, float)
DEFINE_SWIG_INTERFACE_FUNCTION_1D(Float64, double, double)
DEFINE_SWIG_INTERFACE_FUNCTION_1D(Int32, int, int)
DEFINE_SWIG_INTERFACE_FUNCTION_1D(Int64, long long, long)
